services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Krutu@2001
      MYSQL_DATABASE: task_manager1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    environment:
      FLASK_APP: app1.app
      FLASK_ENV: production
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:Krutu%402001@db/task_manager1
      SECRET_KEY: your_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
#    working_dir: /app1
    command: ["sh", "-c", "python wait-for-it.py db 3306 && python -m flask run --host=0.0.0.0"]
#    command: ["python", "wait-for-it.py", "db", "3307", "&&", "python","-m","flask", "run", "--host=0.0.0.0"]

  test:
    build:
      context: .
    container_name: task_manager1_test
    command: ["sh", "-c", "python wait-for-it.py db 3306 && pytest"]
#    command: [ "python", "wait-for-it.py", "db", "3307", "&&", "pytest" ]
    environment:
      FLASK_APP: app1.app
      FLASK_ENV: testing
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:Krutu%402001@db/task_manager1
    volumes:
      - .:/task_manager1
    depends_on:
      - db

volumes:
  mysql_data: